[dependencies]

[package]
  cjc-version = "0.56.4"
  compile-option = ""
  description = "nothing here"
  link-option = ""
  name = "juson"
  output-type = "static"
  src-dir = ""
  target-dir = ""
  version = "1.0.0"
  package-configuration = {}
